name: flowser
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.4
  permission_handler: ^10.0.0
  flutter_reactive_ble: ^5.0.2
  web_view_ble:
    path: ../

dev_dependencies:
  #flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

get_cli:
  sub_folder: false

flutter:
  uses-material-design: true

